### ISSUE TITLE
Attempting to modify this for my own purposes

### ISSUE THREAD

**Issue by Gerald-Meyers** [mclarkk/internet-monitor#1]
I have reached a point where I realized that the ping latency was consistently returning None. Going through the likely causes, noticed 'get_ping_msg' was returning " b'Access denied. Option -c requires administrative privileges.\r\n' ".

Did you encounter this issue? If so how did you solve it? It's not very feasible for me to manually run the script each time with administrator privileges. Is there a specific parameter tag I am not aware of that I have to add to the script?

**Comment by mclarkk** [comment]
I did not experience this problem on macOS or Raspbian. Can the user you run the program as normally run ping without administrative privileges?

**Comment by Gerald-Meyers** [comment]
This is in windows 10. I am running this from my PC in pycharm using python 3.8.

What is the purpose of the '-c 1' in the ping command?

**Comment by mclarkk** [comment]
From the ping man page:

```
-c count
             Stop after sending (and receiving) count ECHO_RESPONSE packets.
             If this option is not specified, ping will operate until inter-
             rupted.  If this option is specified in conjunction with ping
             sweeps, each sweep will consist of count packets.
```

In other words, `c -1` sends one ping packet and reports the result to the caller (in this case, Python) instead of running indefinitely.

If you open the terminal (e.g., Command Prompt) and try typing `ping -c 1 8.8.8.8`, what happens?

**Comment by Gerald-Meyers** [comment]
When I run the command manually through a cmd terminal without admin privileges, I get the specified error. With admin it runs just fine. I have been looking for a solution to do this automatically without having to manually run the script with admin privileges. 

I hate windows sometimes.

**Comment by mclarkk** [comment]
I'm not sure I understand the constraints you are working under. Why doesn't running the script from an admin command prompt, or from a PyCharm instance run with administrative privileges, achieve your goals?

**Comment by Gerald-Meyers** [comment]
-_- Running pycharm with admin solved it. I hate windows.

Thanks for your help. Hopefully I can figure out what is up with my internet now.

**Comment by mclarkk** [comment]
I'm glad you found something that worked! Good luck troubleshooting your internet connection :)
